version: "3.9"

services:
  fdb:
    container_name: datalayers-cluster-fdb
    image: foundationdb/foundationdb:7.3.27
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "4500"]
      interval: 3s
      timeout: 1s
      retries: 10
    networks:
      - datalayers-cluster-network

  fdb-helper:
    container_name: datalayers-cluster-fdb-helper
    image: datalayers/datalayers-exporter:nightly
    healthcheck:
      test: ["CMD", "fdbcli", "-exec", "status"]
      interval: 3s
      timeout: 1s
      retries: 10
    volumes:
      - ./fdb.cluster:/etc/foundationdb/fdb.cluster
    depends_on:
      fdb:
        condition: service_healthy
    entrypoint:
      - /bin/bash
      - -c
      - |
        fdbcli --exec "configure new single ssd-rocksdb-v1"
    networks:
      - datalayers-cluster-network

  datalayers:
    image: datalayers/datalayers:nightly
    environment:
      - DATALAYERS_SERVER__AUTH__USERNAME=admin
      - DATALAYERS_SERVER__AUTH__PASSWORD=public
      - DATALAYERS_STORAGE__TYPE=fdb
      - DATALAYERS_SERVER__STANDALONE=false
    volumes:
      - ./fdb.cluster:/etc/foundationdb/fdb.cluster
    depends_on:
      fdb-helper:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "dlsql", "-u", "admin", "-p", "public"]
      interval: 5s
      timeout: 5s
      retries: 12
    entrypoint:
      - bash
      - -c
      - |
        export DATALAYERS_NODE__NAME="$(hostname -i):8366"
        datalayers
    networks:
      - datalayers-cluster-network

  prometheus:
    container_name: datalayers-cluster-prometheus
    image: prom/prometheus:v2.30.3
    ports:
      - 29090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
      - --storage.tsdb.retention.size=20GB
    networks:
      - datalayers-cluster-network

  grafana:
    container_name: datalayers-cluster-grafana
    image: grafana/grafana:11.0.0
    ports:
      - 23000:3000
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-datalayers-datasource
    volumes:
      # https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/#default-paths
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/grafana-datalayers-datasource.yaml
      - ./grafana/providers.yaml:/etc/grafana/provisioning/dashboards/grafana-datalayers-datasource.yaml
      - ./grafana/dashboard.json:/var/lib/grafana/dashboards/grafana-datalayers-datasource/dashboard.json
      - ./grafana/grafana-datalayers-datasource:/var/lib/grafana/plugins/grafana-datalayers-datasource
    networks:
      - datalayers-cluster-network

  web-proxy:
    container_name: datalayers-cluster-proxy
    image: nginx:latest
    ports:
      - "28361:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      datalayers:
        condition: service_healthy
    networks:
      - datalayers-cluster-network

networks:
  datalayers-cluster-network:
    driver: bridge
