version: "3.9"

services:
  fdb:
    container_name: datalayers-cluster-fdb
    image: foundationdb/foundationdb:7.1.31
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "4500"]
      interval: 3s
      timeout: 1s
      retries: 10
    networks:
      - datalayers-cluster-network

  datalayers:
    image: datalayers/datalayers:nightly
    environment:
      - DATALAYERS_SERVER__AUTH__USERNAME=admin
      - DATALAYERS_SERVER__AUTH__PASSWORD=public
      - DATALAYERS_STORAGE__TYPE=fdb
    volumes:
      - ./fdb.cluster:/etc/foundationdb/fdb.cluster
    depends_on:
      fdb:
        condition: service_healthy
    command:
      - /bin/bash
      - -c
      - |
        fdbcli --exec "configure new single ssd-rocksdb-v1"
        export DATALAYERS_NODE__NAME="$(hostname -i):8366"
        datalayers
    networks:
      - datalayers-cluster-network

  grafana:
    container_name: datalayers-cluster-grafana
    image: grafana/grafana:10.2.3
    ports:
      - 30300:3000
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=datalayers
    volumes:
      ## https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/#default-paths
      - ./grafana/datasource.yaml://etc/grafana/provisioning/datasources/datalayers.yaml
      - ./grafana/datalayers:/var/lib/grafana/plugins/datalayers
    networks:
      - datalayers-cluster-network

  web-proxy:
    container_name: datalayers-cluster-proxy
    image: nginx:latest
    ports:
      - "18361:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - datalayers-cluster-network

networks:
  datalayers-cluster-network:
    driver: bridge
