version: "3.9"

services:
  fdb:
    container_name: datalayers-fdb
    image: foundationdb/foundationdb:7.3.26
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "4500"]
      interval: 3s
      timeout: 1s
      retries: 10

    networks:
      - datalayers-network

  datalayers:
    container_name: datalayers
    image: datalayers/datalayers:nightly 
    ports:
      - 18308:3308
    env_file:
      - .env
    environment:
      - DATALAYERS_SERVER__AUTH__USERNAME=admin
      - DATALAYERS_SERVER__AUTH__PASSWORD=public
      - DATALAYERS_STORAGE__TYPE=fbd
    volumes:
      - ./fdb.cluster:/etc/foundationdb/fdb.cluster
    depends_on:
      fdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "dlsql", "-u", "admin", "-p", "public", "-c", "show databases"]
      interval: 5s
      timeout: 5s
      retries: 12
    command:
      - /bin/bash
      - -c
      - |
        fdbcli --exec "configure new single ssd-rocksdb-v1"
        datalayers
    networks:
      - datalayers-network

  adapter:
    container_name: datalayers-adapter
    image: datalayers/datalayers-adapter:nightly
    ports:
      - 18333:3333
    depends_on:
      datalayers:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATALAYERS_ADAPTER_PROMETHEUS__HOST=prometheus
      - DATALAYERS_ADAPTER_DATALAYERS__ADDRESS=http://datalayers:3308
      - DATALAYERS_ADAPTER_DATALAYERS__USERNAME=admin
      - DATALAYERS_ADAPTER_DATALAYERS__PASSWORD=public
      - RUST_LOG=debug
    networks:
      - datalayers-network

  exporter:
    container_name: datalayers-exporter
    image: datalayers/datalayers-exporter:nightly
    env_file:
      - .env
    depends_on:
      datalayers:
        condition: service_healthy
    volumes:
      - ./fdb.cluster:/etc/foundationdb/fdb.cluster
    networks:
      - datalayers-network

  prometheus:
    container_name: datalayers-prometheus
    image: prom/prometheus:v2.30.3
    ports:
      - 30900:9090
    env_file:
      - .env
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
      - --storage.tsdb.retention.size=20GB
    networks:
      - datalayers-network

  grafana:
    container_name: datalayers-grafana
    image: grafana/grafana:10.2.3
    ports:
      - 30300:3000
    env_file:
      - .env
    volumes:
      ## https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/#default-paths
      - ./grafana/datasource.yaml://etc/grafana/provisioning/datasources/datalayers.yaml
      - ./grafana/providers.yaml://etc/grafana/provisioning/dashboards/datalayers.yaml
      - ./grafana/dashboard.json:/var/lib/grafana/dashboards/datalayers/dashboard.json
    networks:
      - datalayers-network

networks:
  datalayers-network:
    name: datalayers-network
    driver: bridge
