version: "3.9"

services:
  datalayers:
    container_name: datalayers
    image: datalayers/datalayers:nightly
    ports:
      - 18308:3308
    env_file:
      - .env
    environment:
      - DATALAYERS_SERVER__AUTH__USERNAME=admin
      - DATALAYERS_SERVER__AUTH__PASSWORD=public
      - DATALAYERS_STORAGE__TYPE=local
    healthcheck:
      test: ["CMD", "dlsql", "-u", "admin", "-p", "public", "-c", "show databases"]
      interval: 5s
      timeout: 5s
      retries: 12
    command:
      - /bin/bash
      - -c
      - |
        datalayers --standalone
    networks:
      - datalayers-network

  adapter:
    container_name: datalayers-adapter
    image: datalayers/datalayers-adapter:nightly
    ports:
      - 18333:3333
    depends_on:
      datalayers:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATALAYERS_ADAPTER_PROMETHEUS__HOST=prometheus
      - DATALAYERS_ADAPTER_DATALAYERS__ADDRESS=http://datalayers:3308
      - DATALAYERS_ADAPTER_DATALAYERS__USERNAME=admin
      - DATALAYERS_ADAPTER_DATALAYERS__PASSWORD=public
      - RUST_LOG=debug
    networks:
      - datalayers-network

  grafana:
    container_name: datalayers-grafana
    image: grafana/grafana:10.2.3
    ports:
      - 30300:3000
    env_file:
      - .env
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=datalayers
      - GF_DEFAULT_APP_MODE=development
    volumes:
      ## https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/#default-paths
      - ./grafana/datasource.yaml://etc/grafana/provisioning/datasources/datalayers.yaml
      - ./grafana/datalayers:/var/lib/grafana/plugins/datalayers
    networks:
      - datalayers-network

networks:
  datalayers-network:
    name: datalayers-network
    driver: bridge
