global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 1m
scrape_configs:
- job_name: foundationDB
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - exporter:9555
