{
 "title": "Datalayers",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values({job=\"datalayers\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingestion(rows)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(datalayers_ingest_rows{instance=~\"$instance\"}[1m] offset 1m))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries(times)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(datalayers_select_total{instance=~\"$instance\"}[1m] offset 1m))",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Flush parallelism limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(datalayers_flush_concurrence_limit{instance=~\"$instance\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Flushes in progress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(datalayers_flush_running_length{instance=~\"$instance\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Maximum parallelism for compaction",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(datalayers_compact_concurrence_limit{instance=~\"$instance\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "The number of Compaction",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(datalayers_compact_running_length{instance=~\"$instance\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Number of Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(instance) (datalayers_cpu_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "datalayers_memory_usage{instance=~\"$instance\", role=\"stateless\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(datalayers_memory_usage{instance=~\"$instance\", role=\"stateless\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Write QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "rate(datalayers_ingest_rows{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(datalayers_ingest_rows{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Query QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Times" } },
   "targets": [
    {
     "expr": "rate(datalayers_select_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(datalayers_select_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Hit rate of Statistics cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "parquet_meta_cache_hit_total{instance=~\"$instance\"} / (parquet_meta_cache_hit_total{instance=~\"$instance\"} + parquet_meta_cache_miss_total{instance=~\"$instance\"}) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(parquet_meta_cache_hit_total{instance=~\"$instance\"}) / (sum(parquet_meta_cache_hit_total{instance=~\"$instance\"}) + sum(parquet_meta_cache_miss_total{instance=~\"$instance\"})) * 100",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Length of compact running",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "datalayers_compact_running_length{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(datalayers_compact_running_length{instance=~\"$instance\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Length of compact pending",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "datalayers_compact_pending_length{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(datalayers_compact_pending_length{instance=~\"$instance\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Length of flush running",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "datalayers_flush_running_length{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(datalayers_flush_running_length{instance=~\"$instance\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Length of flush pending ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "datalayers_flush_pending_length{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(datalayers_flush_pending_length{instance=~\"$instance\"})",
     "legendFormat": "All"
    }
   ]
  },
  { "title": "Hybird Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory file cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(datalayers_memory_op_total{op=\"hit\",name=\"Datalayers.file_cache\",instance=~\"$instance\"}) by (instance) / sum(datalayers_memory_op_total{op=~\"(hit|miss)\",name=\"Datalayers.file_cache\",instance=~\"$instance\"}) by (instance)) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(datalayers_memory_op_total{op=\"hit\",name=\"Datalayers.file_cache\",instance=~\"$instance\"}) by (job) / sum(datalayers_memory_op_total{op=~\"(hit|miss)\",name=\"Datalayers.file_cache\",instance=~\"$instance\"}) by (job)) * 100",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "File cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(datalayers_storage_op_total{op=\"hit\",name=\"Datalayers.file_cache\",instance=~\"$instance\"}) by (instance) / sum(datalayers_storage_op_total{op=~\"(hit|miss)\",name=\"Datalayers.file_cache\",instance=~\"$instance\"}) by (instance)) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(datalayers_storage_op_total{op=\"hit\",name=\"Datalayers.file_cache\",instance=~\"$instance\"}) by (job) / sum(datalayers_storage_op_total{op=~\"(hit|miss)\",name=\"Datalayers.file_cache\",instance=~\"$instance\"}) by (job)) * 100",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Hybrid file cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(datalayers_hybrid_op_total{op=\"hit\",name=\"Datalayers.file_cache\",instance=~\"$instance\"}) by (instance) / sum(datalayers_hybrid_op_total{op=~\"(hit|miss)\",name=\"Datalayers.file_cache\",instance=~\"$instance\"}) by (instance)) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(datalayers_hybrid_op_total{op=\"hit\",name=\"Datalayers.file_cache\",instance=~\"$instance\"}) by (job) / sum(datalayers_hybrid_op_total{op=~\"(hit|miss)\",name=\"Datalayers.file_cache\",instance=~\"$instance\"}) by (job)) * 100",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Memory file meta cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(datalayers_memory_op_total{op=\"hit\",name=\"Datalayers.file_meta_cache\",instance=~\"$instance\"}) by (instance) / sum(datalayers_memory_op_total{op=~\"(hit|miss)\",name=\"Datalayers.file_meta_cache\",instance=~\"$instance\"}) by (instance)) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(datalayers_memory_op_total{op=\"hit\",name=\"Datalayers.file_meta_cache\",instance=~\"$instance\"}) by (job) / sum(datalayers_memory_op_total{op=~\"(hit|miss)\",name=\"Datalayers.file_meta_cache\",instance=~\"$instance\"}) by (job)) * 100",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Storage file meta cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(datalayers_storage_op_total{op=\"hit\",name=\"Datalayers.file_meta_cache\",instance=~\"$instance\"}) by (instance) / sum(datalayers_storage_op_total{op=~\"(hit|miss)\",name=\"Datalayers.file_meta_cache\",instance=~\"$instance\"}) by (instance)) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(datalayers_storage_op_total{op=\"hit\",name=\"Datalayers.file_meta_cache\",instance=~\"$instance\"}) by (job) / sum(datalayers_storage_op_total{op=~\"(hit|miss)\",name=\"Datalayers.file_meta_cache\",instance=~\"$instance\"}) by (job)) * 100",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Hybrid file meta cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(datalayers_hybrid_op_total{op=\"hit\",name=\"Datalayers.file_meta_cache\",instance=~\"$instance\"}) by (instance) / sum(datalayers_hybrid_op_total{op=~\"(hit|miss)\",name=\"Datalayers.file_meta_cache\",instance=~\"$instance\"}) by (instance)) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(datalayers_hybrid_op_total{op=\"hit\",name=\"Datalayers.file_meta_cache\",instance=~\"$instance\"}) by (job) / sum(datalayers_hybrid_op_total{op=~\"(hit|miss)\",name=\"Datalayers.file_meta_cache\",instance=~\"$instance\"}) by (job)) * 100",
     "legendFormat": "All"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Latency of flushing per 10MB",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "times" } },
   "targets": [
    {
     "expr": "sum(latency_flush_per_10m_milliseconds_bucket{instance=~\"$instance\"}) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency of compact per 10MB",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "times" } },
   "targets": [
    {
     "expr": "sum(latency_compact_per_10m_milliseconds_bucket{instance=~\"$instance\"}) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of Datalayers panic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "datalayers_panic_total{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(datalayers_panic_total{instance=~\"$instance\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(datalayers_cpu_total{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(floor(datalayers_cpu_usage{instance=~\"$instance\"} /100) / datalayers_cpu_total{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(datalayers_memory_total{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(datalayers_memory_usage{instance=~\"$instance\"} / 1024 / 1024 / datalayers_memory_total{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}