{
 "title": "datalayers",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values({job=\"datalayers\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Momery Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "memory_usage{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(memory_usage{instance=~\"$instance\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "QPS for writes(rows)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "rate(schemaless_request_total{instance=~\"$instance\"}[$__rate_interval]) + rate(schemaless_insert_rows_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(schemaless_request_total{instance=~\"$instance\"}[$__rate_interval]) + rate(schemaless_insert_rows_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "QPS for SQL Queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Times" } },
   "targets": [
    {
     "expr": "rate(select_request_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(select_request_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "QPS for SQL inserts(rows)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "rate(insert_rows_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(insert_rows_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "QPS for schemaless writes(rows)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Rows" } },
   "targets": [
    {
     "expr": "rate(schemaless_request_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(schemaless_request_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Count of current flush queue",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Tasks" } },
   "targets": [
    {
     "expr": "flush_queue_total{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(flush_queue_total{instance=~\"$instance\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Total Point of memtable",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "memtable_pk_total{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(memtable_pk_total{instance=~\"$instance\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "QPS  for SQL inserts(times)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(insert_request_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(insert_request_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "QPS for schemaless queries(times)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(schemaless_request_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(schemaless_request_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Total size of current immutable",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "immutable_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(immutable_size_bytes{instance=~\"$instance\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Total rows  of memtable",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Rows" } },
   "targets": [
    {
     "expr": "memtable_rows_total{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(memtable_rows_total{instance=~\"$instance\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Total number of rows in immutable",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Rows" } },
   "targets": [
    {
     "expr": "immutable_rows_total{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(immutable_rows_total{instance=~\"$instance\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Size of the memtable in memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "memtable_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(memtable_size_bytes{instance=~\"$instance\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Time of flushing repack",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "flush_repack_delay{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(flush_repack_delay{instance=~\"$instance\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Time of flushing delay",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "flush_delay{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(flush_delay{instance=~\"$instance\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Parquet meta chache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "parquet_meta_cache_hit_total{instance=~\"$instance\"} / (parquet_meta_cache_hit_total{instance=~\"$instance\"} + parquet_meta_cache_miss_total{instance=~\"$instance\"}) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(parquet_meta_cache_hit_total{instance=~\"$instance\"}) / (sum(parquet_meta_cache_hit_total{instance=~\"$instance\"}) + sum(parquet_meta_cache_miss_total{instance=~\"$instance\"})) * 100",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Parquet statistics cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "parquet_statistics_cache_hit_total{instance=~\"$instance\"} / (parquet_statistics_cache_hit_total{instance=~\"$instance\"} + parquet_statistics_cache_miss_total{instance=~\"$instance\"}) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(parquet_statistics_cache_hit_total{instance=~\"$instance\"}) / (sum(parquet_statistics_cache_hit_total{instance=~\"$instance\"}) + sum(parquet_statistics_cache_miss_total{instance=~\"$instance\"})) * 100",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Object store cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "object_store_meta_cache_hit_total{instance=~\"$instance\"} / (object_store_meta_cache_hit_total{instance=~\"$instance\"} + object_store_meta_cache_miss_total{instance=~\"$instance\"}) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(object_store_meta_cache_hit_total{instance=~\"$instance\"}) / (sum(object_store_meta_cache_hit_total{instance=~\"$instance\"}) + sum(object_store_meta_cache_miss_total{instance=~\"$instance\"})) * 100",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Time consumed by memtable sorting",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(latency_memtable_sort_milliseconds_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time of immutable to flushing",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(latency_immutable_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time spent on flushing Parquet files to disk",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(latency_flush_write_file_milliseconds_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}