## https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file
apiVersion: 1
datasources:
  - name: Datalayers
    type: grafana-datalayers-datasource
    orgId: 1
    uid: "grafana-datalayers-datasource"
    url: http://datalayers:8360
    jsonData:
      host: "datalayers:8360"
      selectedAuthType: "username/password"
      username: "admin"
      metadata:
        - database: "demo"
    secureJsonData:
      password: "public"
    version: 1
    editable: true
    isDefault: true

  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: "prom"
    url: http://prometheus:9090
    isDefault: false
    version: 1
    editable: true
