## https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file
apiVersion: 1
datasources:
  - name: Datalayers
    type: datalayers
    orgId: 1
    url: http://datalayers:8360
    jsonData:
      host: "datalayers:8360"
      selectedAuthType: "username/password"
      username: "admin"
    secureJsonData:
      password: "public"
    version: 1
    editable: true
    isDefault: true
