{
 "title": "Datalayers Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingestion(rows)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(datalayers_ingest_rows_total{}[10s] offset 10s))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries(times)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(datalayers_select_total{}[10s] offset 10s))",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Memory Usage of System",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(datalayers_system_memory_usage{} / datalayers_system_memory_total{}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage of System",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "datalayers_system_cpu_usage{} / 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(instance) (datalayers_cpu_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panic",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(datalayers_panic_total{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage of Datalayers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "datalayers_memory_usage{role=\"stateless\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage of Datalayers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "datalayers_cpu_usage{role=\"stateless\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "QPS of Ingestion",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "rate(datalayers_ingest_rows_total{}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(datalayers_ingest_rows_total{}[$__rate_interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Queries per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Times" } },
   "targets": [
    {
     "expr": "rate(datalayers_select_total{}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(datalayers_select_total{}[$__rate_interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "The number of compaction tasks in progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "datalayers_compact_running_length{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(datalayers_compact_running_length{})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "The number of flush tasks in progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "datalayers_flush_running_length{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(datalayers_flush_running_length{})",
     "legendFormat": "All"
    },
    {
     "expr": "sum(datalayers_flush_concurrence_limit{})",
     "legendFormat": "Max concurrence limit"
    }
   ]
  },
  {
   "title": "Hit rate of Parquet Meta cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(parquet_meta_op_total{op=\"hit\"}[$__rate_interval])) by (type) / sum(rate(parquet_meta_op_total{op=~\"hit|miss\"}[$__rate_interval])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The backlog of compaction tasks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "datalayers_compact_pending_length{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(datalayers_compact_pending_length{})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "The backlog of flush tasks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "datalayers_flush_pending_length{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(datalayers_flush_pending_length{})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Memory Usage of Parquet Metadata Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(datalayers_parquet_meta_cache_usage{})",
     "legendFormat": "memory_usage"
    },
    {
     "expr": "sum(datalayers_parquet_meta_cache_usage{}) by (instance)",
     "legendFormat": "{{instance}}_memory_usage"
    },
    {
     "expr": "sum(datalayers_parquet_meta_cache_config_size)",
     "legendFormat": "Max Memory Limit"
    }
   ]
  },
  { "title": "Hybird Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Hit Rate of Memory cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_memory_op_total{op=\"hit\", name=\"Datalayers.file_cache\"}[$__rate_interval])) by (name) / sum(rate(foyer_memory_op_total{op=~\"(hit|miss)\", name=\"Datalayers.file_cache\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Hit rate of Disk Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_storage_op_total{op=\"hit\", name=\"Datalayers.file_cache\"}[$__rate_interval])) by (name) / sum(rate(foyer_storage_op_total{op=~\"(hit|miss)\", name=\"Datalayers.file_cache\"}[$__rate_interval])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hit Rate of Hybrid File Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_hybrid_op_total{op=\"hit\",name=\"Datalayers.file_cache\"}[$__rate_interval])) by (name) / sum(rate(foyer_hybrid_op_total{op=~\"(hit|miss)\", name=\"Datalayers.file_cache\"}[$__rate_interval])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage of File Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(foyer_memory_usage{name=\"Datalayers.file_cache\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(datalayers_hybrid_cached_file_memory_config_size)",
     "legendFormat": "Max Memory Limit"
    },
    {
     "expr": "sum(foyer_memory_usage{name=\"Datalayers.file_cache\"}) ",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Hit Rate of Memory file_meta cache ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_memory_op_total{op=\"hit\", name=\"Datalayers.file_meta_cache\"}[$__rate_interval])) by (name) / sum(rate(foyer_memory_op_total{op=~\"(hit|miss)\", name=\"Datalayers.file_meta_cache\"}[$__rate_interval])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hit Rate of Disk file_meta cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_storage_op_total{op=\"hit\", name=\"Datalayers.file_meta_cache\"}[$__rate_interval])) by (name) or vector(0) / sum(rate(foyer_storage_op_total{op=~\"(hit|miss)\", name=\"Datalayers.file_meta_cache\"}[$__rate_interval])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hit Rate of Hybrid file_meta cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_hybrid_op_total{op=\"hit\", name=\"Datalayers.file_meta_cache\"}[$__rate_interval])) by (name) / sum(rate(foyer_hybrid_op_total{op=~\"(hit|miss)\", name=\"Datalayers.file_meta_cache\"}[$__rate_interval])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage of File Meta Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(foyer_memory_usage{name=\"Datalayers.file_meta_cache\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hybrid Cache Op",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_hybrid_op_total[$__rate_interval])) by (name, op)",
     "legendFormat": "{{name}} - hybrid - {{op}}"
    }
   ]
  },
  {
   "title": "Memory OP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_memory_op_total[$__rate_interval])) by (name, op)",
     "legendFormat": "{{name}} - memory - {{op}}"
    }
   ]
  },
  {
   "title": "Serde Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(foyer_storage_entry_serde_duration_bucket[$__rate_interval])) by (le, name, op))",
     "legendFormat": "p50 - {{name}} - storage - {{op}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(foyer_storage_entry_serde_duration_bucket[$__rate_interval])) by (le, name, op))",
     "legendFormat": "p90 - {{name}} - storage - {{op}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(foyer_storage_entry_serde_duration_bucket[$__rate_interval])) by (le, name, op))",
     "legendFormat": "p99 - {{name}} - storage - {{op}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(foyer_storage_entry_serde_duration_bucket[$__rate_interval])) by (le, name, op))",
     "legendFormat": "pmax - {{name}} - storage - {{op}}"
    },
    {
     "expr": "sum(rate(foyer_storage_entry_serde_duration_sum[$__rate_interval])) by (le, name, op) / sum(rate(foyer_storage_entry_serde_duration_count[$__rate_interval])) by (le, name, op)",
     "legendFormat": "pavg - {{name}} - storage - {{op}}"
    }
   ]
  },
  {
   "title": "Disk IO Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 36 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(foyer_storage_disk_io_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "p50 - {{name}} - disk io - {{op}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(foyer_storage_disk_io_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "p90 - {{name}} - disk io - {{op}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(foyer_storage_disk_io_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "p99 - {{name}} - disk io - {{op}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(foyer_storage_disk_io_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "pmax - {{name}} - disk io - {{op}}"
    },
    {
     "expr": "sum(rate(foyer_storage_disk_io_duration_sum[$__rate_interval])) by (le, name, op) / sum(rate(foyer_storage_disk_io_duration_count[$__rate_interval])) by (le, name, op)",
     "legendFormat": "pavg - {{name}} - disk io - {{op}}"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Latency of flushing per 10MB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(latency_flush_per_10m_milliseconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(latency_flush_per_10m_milliseconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(latency_flush_per_10m_milliseconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(latency_flush_per_10m_milliseconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "pmax"
    }
   ]
  },
  {
   "title": "Latency of compact per 10MB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(latency_compact_per_10m_milliseconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(latency_compact_per_10m_milliseconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(latency_compact_per_10m_milliseconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(latency_compact_per_10m_milliseconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "pmax"
    }
   ]
  }
 ]
}