{
 "title": "Datalayers Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingestion(rows)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(datalayers_ingest_rows_total{}[10s] offset 10s))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries(times)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(datalayers_select_total{}[10s] offset 10s))",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Memory Usage of System",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(datalayers_system_memory_usage{} / datalayers_system_memory_total{}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage of System",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "datalayers_system_cpu_usage{} / 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(instance) (datalayers_cpu_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panic",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(datalayers_panic_total{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage of Datalayers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "datalayers_memory_usage{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage of Datalayers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "datalayers_cpu_usage{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "QPS of Ingestion",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "rate(datalayers_ingest_rows_total{}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(datalayers_ingest_rows_total{}[$__rate_interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Queries per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Times" } },
   "targets": [
    {
     "expr": "rate(datalayers_select_total{}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(datalayers_select_total{}[$__rate_interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "The number of compaction tasks in progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "datalayers_compact_running_length{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(datalayers_compact_running_length{})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "The number of flush tasks in progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "datalayers_flush_running_length{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(datalayers_flush_running_length{})",
     "legendFormat": "All"
    },
    {
     "expr": "sum(datalayers_flush_concurrence_limit{})",
     "legendFormat": "Max concurrence limit"
    }
   ]
  },
  {
   "title": "Hit rate of Parquet Meta cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(parquet_meta_op_total{op=\"hit\"}[$__rate_interval])) by (type) / sum(rate(parquet_meta_op_total{}[$__rate_interval])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hit rate of Last value cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(datalayers_last_value_cache_op_total{op=\"hit\"}[$__rate_interval]))/ sum(rate(datalayers_last_value_cache_op_total{}[$__rate_interval])) ",
     "legendFormat": "hit rate of last cache value"
    }
   ]
  },
  {
   "title": "The backlog of compaction tasks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "datalayers_compact_pending_length{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(datalayers_compact_pending_length{})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "The backlog of flush tasks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "datalayers_flush_pending_length{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(datalayers_flush_pending_length{})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Memory Usage of Parquet Metadata Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(datalayers_parquet_meta_cache_usage{})",
     "legendFormat": "memory_usage"
    },
    {
     "expr": "sum(datalayers_parquet_meta_cache_usage{}) by (instance)",
     "legendFormat": "{{instance}}_memory_usage"
    },
    {
     "expr": "sum(datalayers_parquet_meta_cache_config_size)",
     "legendFormat": "Max Memory Limit"
    }
   ]
  },
  {
   "title": "Memory Usage of Last Value Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(datalayers_last_value_cache_usage{})",
     "legendFormat": "memory_usage"
    },
    {
     "expr": "sum(datalayers_last_value_cache_usage{}) by (instance)",
     "legendFormat": "{{instance}}_memory_usage"
    },
    {
     "expr": "sum(datalayers_last_value_cache_config_size)",
     "legendFormat": "Max Memory Limit"
    }
   ]
  },
  { "title": "Hybird Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Hit Rate of Memory cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_memory_op_total{op=\"hit\", name=\"Datalayers.file_cache\"}[$__rate_interval])) by (name) / sum(rate(foyer_memory_op_total{op=~\"(hit|miss)\", name=\"Datalayers.file_cache\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Hit rate of Disk Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_storage_op_total{op=\"hit\", name=\"Datalayers.file_cache\"}[$__rate_interval])) by (name) / sum(rate(foyer_storage_op_total{op=~\"(hit|miss)\", name=\"Datalayers.file_cache\"}[$__rate_interval])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hit Rate of Hybrid File Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_hybrid_op_total{op=\"hit\",name=\"Datalayers.file_cache\"}[$__rate_interval])) by (name) / sum(rate(foyer_hybrid_op_total{op=~\"(hit|miss)\", name=\"Datalayers.file_cache\"}[$__rate_interval])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage of File Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(foyer_memory_usage{name=\"Datalayers.file_cache\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(datalayers_hybrid_cached_file_memory_config_size)",
     "legendFormat": "Max Memory Limit"
    },
    {
     "expr": "sum(foyer_memory_usage{name=\"Datalayers.file_cache\"}) ",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Hybrid Cache Op",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_hybrid_op_total[$__rate_interval])) by (name, op)",
     "legendFormat": "{{name}} - hybrid - {{op}}"
    }
   ]
  },
  {
   "title": "Memory OP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_memory_op_total[$__rate_interval])) by (name, op)",
     "legendFormat": "{{name}} - memory - {{op}}"
    }
   ]
  },
  {
   "title": "Op Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_storage_disk_io_bytes_total[$__rate_interval])) by (name, op, extra) ",
     "legendFormat": "{{name}} storage - {{op}} {{extra}}"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_storage_disk_io_total[$__rate_interval])) by (name, op)",
     "legendFormat": "{{name}} - disk io - {{op}}"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Incoming and outgoing network traffic per interface",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(datalayers_network_rx_bytes_total{}[$__rate_interval])*8 ",
     "legendFormat": "{{instance}} - {{device}} - Rx in"
    },
    {
     "expr": "rate(datalayers_network_tx_bytes_total{}[$__rate_interval])*8 ",
     "legendFormat": "{{instance}} - {{device}} - Tx out"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization",
   "type": "timeseries",
   "description": "Percentage of time the disk was actively processing I/O operations",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(datalayers_disk_io_ticks_total{type=\"disk\"}[$__rate_interval])/10",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "description": "Disk I/O throughput per device",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(datalayers_disk_read_bytes_total{type=\"disk\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{device}} - Read"
    },
    {
     "expr": "irate(datalayers_disk_write_bytes_total{type=\"disk\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{device}} - Write"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "description": "Disk I/O operations per second for each device",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(datalayers_disk_read_total{type=\"disk\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{device}} - Read"
    },
    {
     "expr": "irate(datalayers_disk_write_total{type=\"disk\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{device}} - Write"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Percentage of filesystem space used for each mounted device",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "datalayers_disk_usage_percent{}",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  }
 ]
}