{
 "title": "FoundationDB",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(fdb_database_available, namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(fdb_database_available{namespace=\"$namespace\"}, job)"
    }
   },
   {
    "name": "storage_processes",
    "label": "storage processes",
    "query": {
     "query": "label_values(fdb_process_storage_data_lag_seconds{namespace=\"$namespace\", job=\"$job\"}, address) "
    }
   },
   {
    "name": "log_processes",
    "label": "log processes",
    "query": {
     "query": "label_values(fdb_process_log_input_bytes_total{namespace=\"$namespace\", job=\"$job\"}, address) "
    }
   },
   { "name": "interval", "query": "30s,1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database is Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fdb_database_available{namespace=\"$namespace\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Database is Locked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fdb_database_locked{namespace=\"$namespace\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(fdb_clients_total{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporter Latency",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(fdb_exporter_latency_seconds{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  { "title": "Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(fdb_workload_operations_read_requests_total{namespace=\"$namespace\", job=\"$job\"}[$interval]))",
     "legendFormat": "Read requests"
    },
    {
     "expr": "sum(rate(fdb_workload_operations_reads_total{namespace=\"$namespace\", job=\"$job\"}[$interval]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(fdb_workload_operations_writes_total{namespace=\"$namespace\", job=\"$job\"}[$interval]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(fdb_workload_transactions_started_total{namespace=\"$namespace\", job=\"$job\"}[$interval]))",
     "legendFormat": "Transactions started"
    },
    {
     "expr": "sum(rate(fdb_workload_transactions_committed_total{namespace=\"$namespace\", job=\"$job\"}[$interval]))",
     "legendFormat": "Transactions committed"
    }
   ]
  },
  {
   "title": "Transaction Conflicts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(fdb_workload_transactions_conflicted_total{namespace=\"$namespace\", job=\"$job\"}[$interval]))",
     "legendFormat": "Transactions conflicted"
    }
   ]
  },
  {
   "title": "Keys Read",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(fdb_workload_keys_read_total{namespace=\"$namespace\", job=\"$job\"}[$interval]))",
     "legendFormat": "Keys read"
    }
   ]
  },
  {
   "title": "Data",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(fdb_workload_bytes_read_total{namespace=\"$namespace\", job=\"$job\"}[$interval]))",
     "legendFormat": "Bytes read"
    },
    {
     "expr": "sum(rate(fdb_workload_bytes_written_total{namespace=\"$namespace\", job=\"$job\"}[$interval]))",
     "legendFormat": "Bytes written"
    }
   ]
  },
  { "title": "QoS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Performance Limited By",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "fdb_qos_performance_limited_by{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "Transactions per Second Limit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max(fdb_qos_transactions_per_second_limit{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Transactions per second limit"
    },
    {
     "expr": "max(fdb_qos_batch_transactions_per_second_limit{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Batch transactions per second limit"
    }
   ]
  },
  {
   "title": "Released Transactions per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max(fdb_qos_released_transactions_per_second{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Released transactions per second"
    },
    {
     "expr": "max(fdb_qos_batch_released_transactions_per_second{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Batch released transactions per second"
    }
   ]
  },
  {
   "title": "Batch Performance Limited By",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "fdb_qos_batch_performance_limited_by{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "Storage Server Durability Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(fdb_qos_limiting_storage_server_durability_lag_seconds{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Limiting"
    },
    {
     "expr": "max(fdb_qos_worst_storage_server_durability_lag_seconds{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Worst"
    }
   ]
  },
  {
   "title": "Storage Server Data Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(fdb_qos_limiting_storage_server_data_lag_seconds{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Limiting"
    },
    {
     "expr": "max(fdb_qos_worst_storage_server_data_lag_seconds{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Worst"
    }
   ]
  },
  {
   "title": "Storage Server Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(fdb_qos_limiting_storage_server_queue_bytes{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Limiting"
    },
    {
     "expr": "max(fdb_qos_worst_storage_server_queue_bytes{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Worst"
    }
   ]
  },
  {
   "title": "Log Server Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(fdb_qos_worst_log_server_queue_bytes{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Worst"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "fdb_data_state{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Total disk used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(fdb_data_total_disk_used_bytes{namespace=\"$namespace\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Total KV size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(fdb_data_total_kv_size_bytes{namespace=\"$namespace\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Operating space on most full storage server",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(fdb_data_least_operating_space_storage_server_bytes{namespace=\"$namespace\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Operating space on most full log server",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(fdb_data_least_operating_space_log_server_bytes{namespace=\"$namespace\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Moving data in-queue bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(fdb_data_moving_in_queue_bytes{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "In-queue bytes"
    }
   ]
  },
  {
   "title": "Moving data in-flight bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(fdb_data_moving_in_flight_bytes{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "In-flight bytes"
    }
   ]
  },
  {
   "title": "Moving data rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(fdb_data_moving_total_written_bytes{namespace=\"$namespace\", job=\"$job\"}[$interval]))",
     "legendFormat": "Moving data rate"
    }
   ]
  },
  {
   "title": "System KV size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(fdb_data_system_kv_size_bytes{namespace=\"$namespace\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Average partition size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fdb_data_average_partition_size_bytes{namespace=\"$namespace\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fdb_data_partitions_total{namespace=\"$namespace\", job=\"$job\"}"
    }
   ]
  },
  { "title": "Storage Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "$storage_processes Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 46 },
   "repeat": "storage_processes",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(fdb_process_storage_input_bytes_total{namespace=\"$namespace\", job=\"$job\", address=~\"$storage_processes\"}[$interval]))",
     "legendFormat": "Input"
    },
    {
     "expr": "sum(rate(fdb_process_storage_durable_bytes_total{namespace=\"$namespace\", job=\"$job\", address=~\"$storage_processes\"}[$interval]))",
     "legendFormat": "Durable"
    }
   ]
  },
  {
   "title": "Lag",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 46 },
   "repeat": "storage_processes",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(fdb_process_storage_data_lag_seconds{namespace=\"$namespace\", job=\"$job\", address=~\"$storage_processes\"})",
     "legendFormat": "Data lag"
    },
    {
     "expr": "max(fdb_process_storage_durability_lag_seconds{namespace=\"$namespace\", job=\"$job\", address=~\"$storage_processes\"})",
     "legendFormat": "Durability lag"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 46 },
   "repeat": "storage_processes",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(fdb_process_cpu_usage_cores{namespace=\"$namespace\", job=\"$job\", address=~\"$storage_processes\"})",
     "legendFormat": "CPU cores"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 46 },
   "repeat": "storage_processes",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(fdb_process_disk_usage_ratio{namespace=\"$namespace\", job=\"$job\", address=~\"$storage_processes\"})",
     "legendFormat": "Disk utilization"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 46 },
   "repeat": "storage_processes",
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "max(fdb_process_network_megabits_received_rate{namespace=\"$namespace\", job=\"$job\", address=~\"$storage_processes\"} + fdb_process_network_megabits_sent_rate)",
     "legendFormat": "Disk utilization"
    }
   ]
  },
  {
   "title": "Stored Data",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 46 },
   "repeat": "storage_processes",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(fdb_process_storage_stored_bytes{namespace=\"$namespace\", job=\"$job\", address=~\"$storage_processes\"})",
     "legendFormat": "Stored bytes"
    }
   ]
  },
  { "title": "Log Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "$log_processes Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 52 },
   "repeat": "log_processes",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(fdb_process_log_input_bytes_total{namespace=\"$namespace\", job=\"$job\", address=~\"$log_processes\"}[$interval]))",
     "legendFormat": "Input"
    },
    {
     "expr": "sum(rate(fdb_process_log_durable_bytes_total{namespace=\"$namespace\", job=\"$job\", address=~\"$log_processes\"}[$interval]))",
     "legendFormat": "Durable"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 52 },
   "repeat": "log_processes",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(fdb_process_cpu_usage_cores{namespace=\"$namespace\", job=\"$job\", address=~\"$log_processes\"})",
     "legendFormat": "CPU cores"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 52 },
   "repeat": "log_processes",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(fdb_process_disk_usage_ratio{namespace=\"$namespace\", job=\"$job\", address=~\"$log_processes\"})",
     "legendFormat": "Disk utilization"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 52 },
   "repeat": "log_processes",
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "max(fdb_process_network_megabits_received_rate{namespace=\"$namespace\", job=\"$job\", address=~\"$log_processes\"} + fdb_process_network_megabits_sent_rate)",
     "legendFormat": "Disk utilization"
    }
   ]
  },
  { "title": "Latency Probe", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(fdb_latency_probe_read_seconds{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Time to perform a single read"
    }
   ]
  },
  {
   "title": "Commit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(fdb_latency_probe_commit_seconds{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Time to commit a sample transaction"
    }
   ]
  },
  {
   "title": "Transaction Start",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(fdb_latency_probe_transaction_start_seconds{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Time to start a sample transaction at normal priority"
    },
    {
     "expr": "max(fdb_latency_probe_immediate_priority_transaction_start_seconds{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Time to start a sample transaction at system immediate priority"
    },
    {
     "expr": "max(fdb_latency_probe_batch_priority_transaction_start_seconds{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Time to start a sample transaction at batch priority"
    }
   ]
  },
  { "title": "Recovery State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Recovery State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "fdb_recovery_state{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "Active Generations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(fdb_recovery_state_active_generations{namespace=\"$namespace\", job=\"$job\"})"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Processes",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sum(fdb_process_class{namespace=\"$namespace\", job=\"$job\"}) by (address, classType)",
     "legendFormat": "Class"
    },
    {
     "expr": "sum(fdb_process_cpu_usage_cores{namespace=\"$namespace\", job=\"$job\"}) by (address)",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(fdb_process_memory_used_bytes{namespace=\"$namespace\", job=\"$job\"}) by (address)",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(fdb_process_memory_used_bytes{namespace=\"$namespace\", job=\"$job\"} / fdb_process_memory_limit_bytes) by (address)",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "sum(rate(fdb_process_disk_reads_total{namespace=\"$namespace\", job=\"$job\"}[$interval]) + rate(fdb_process_disk_writes_total[$interval])) by (address)",
     "legendFormat": "Disk IO"
    },
    {
     "expr": "sum(1.0 - fdb_process_disk_free_bytes{namespace=\"$namespace\", job=\"$job\"} / fdb_process_disk_total_bytes) by (address)",
     "legendFormat": "Disk Used"
    },
    {
     "expr": "sum(fdb_process_disk_usage_ratio{namespace=\"$namespace\", job=\"$job\"}) by (address)",
     "legendFormat": "Disk Utilization"
    },
    {
     "expr": "sum(fdb_process_network_megabits_received_rate{namespace=\"$namespace\", job=\"$job\"} + fdb_process_network_megabits_sent_rate) by (address)",
     "legendFormat": "Network IO"
    },
    {
     "expr": "sum(fdb_process_network_current_connections_total{namespace=\"$namespace\", job=\"$job\"}) by (address)",
     "legendFormat": "Network Connections"
    },
    {
     "expr": "sum(fdb_process_run_loop_busy_ratio{namespace=\"$namespace\", job=\"$job\"}) by (address)",
     "legendFormat": "Run Loop Utilization"
    }
   ]
  },
  { "title": "Backup State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Backup",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "sum(fdb_backup_tag_is_running_backup{job=\"$job\"}) by (tag)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(fdb_backup_tag_seconds_behind{job=\"$job\"}) by (tag)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(fdb_backup_tag_current_status{job=\"$job\"}) by (tag)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}